<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Acme\\Testkit\\' => array($vendorDir . '/acme/testkit/src'),
    'Acme\\Hello\\' => array($vendorDir . '/acme/hello/src'),
);
