<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit73da8f91c87f59f6735580124d29207c
{
    public static $prefixLengthsPsr4 = array (
        'A' =>
        array (
            'Acme\\Testkit\\' => 13,
            'Acme\\Hello\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Acme\\Testkit\\' =>
        array (
            0 => __DIR__ . '/..' . '/acme/testkit/src',
        ),
        'Acme\\Hello\\' =>
        array (
            0 => __DIR__ . '/..' . '/acme/hello/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit73da8f91c87f59f6735580124d29207c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit73da8f91c87f59f6735580124d29207c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit73da8f91c87f59f6735580124d29207c::$classMap;

        }, null, ClassLoader::class);
    }
}
