<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitVivaceFixturePsr4SharedPrefix
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
        ),
        'M' =>
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Http\\Message\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Monolog\\' =>
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitVivaceFixturePsr4SharedPrefix::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitVivaceFixturePsr4SharedPrefix::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitVivaceFixturePsr4SharedPrefix::$classMap;

        }, null, ClassLoader::class);
    }
}
