<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitVivaceFixture
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'N' =>
        array (
            'Nyholm\\Psr7\\' => 12,
        ),
        'H' =>
        array (
            'Http\\Discovery\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Http\\Message\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Nyholm\\Psr7\\' =>
        array (
            0 => __DIR__ . '/..' . '/nyholm/psr7/src',
        ),
        'Http\\Discovery\\' =>
        array (
            0 => __DIR__ . '/..' . '/php-http/discovery/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Http\\Discovery\\Strategy\\GeneratedDiscoveryStrategy' => __DIR__ . '/..' . '/composer/GeneratedDiscoveryStrategy.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitVivaceFixture::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitVivaceFixture::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitVivaceFixture::$classMap;

        }, null, ClassLoader::class);
    }
}
