<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit177a5b51622bd0aa2b2b1859c3a8496c
{
    public static $files = array (
        '521d5786a5c60a51bbc1bc6020724fec' => __DIR__ . '/../..' . '/wp-content/plugins/soil/src/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' =>
        array (
            'Roots\\Soil\\' => 11,
        ),
        'C' =>
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Roots\\Soil\\' =>
        array (
            0 => __DIR__ . '/../..' . '/wp-content/plugins/soil/src',
        ),
        'Composer\\Installers\\' =>
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $prefixesPsr0 = array (
        'j' =>
        array (
            'johnpbloch\\Composer\\' =>
            array (
                0 => __DIR__ . '/..' . '/johnpbloch/wordpress-core-installer/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit177a5b51622bd0aa2b2b1859c3a8496c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit177a5b51622bd0aa2b2b1859c3a8496c::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit177a5b51622bd0aa2b2b1859c3a8496c::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit177a5b51622bd0aa2b2b1859c3a8496c::$classMap;

        }, null, ClassLoader::class);
    }
}
