<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '521d5786a5c60a51bbc1bc6020724fec' => $baseDir . '/wp-content/plugins/soil/src/helpers.php',
);
