//! One `#[test]` per `tests/fixtures/composer/installer/*.test` fixture,
//! generated by `build.rs` (Riff's approach). See `tests/support` for the
//! runner and `tests/fixtures/composer/installer/ported.txt` for which
//! fixtures are expected to pass.

mod support;

include!(concat!(env!("OUT_DIR"), "/installer_fixtures_generated.rs"));
