<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitVivaceFixture
{
    public static $prefixLengthsPsr4 = array (
        'c' =>
        array (
            'cweagans\\Composer\\' => 18,
        ),
        'P' =>
        array (
            'Psr\\Log\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'cweagans\\Composer\\' =>
        array (
            0 => __DIR__ . '/..' . '/cweagans/composer-patches/src',
            1 => __DIR__ . '/..' . '/cweagans/composer-configurable-plugin/src',
        ),
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitVivaceFixture::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitVivaceFixture::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitVivaceFixture::$classMap;

        }, null, ClassLoader::class);
    }
}
