<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitVivaceFixture
{
    public static $files = array (
        '73d63f9f8d5cdc7313ef8f36cad4b91a' => __DIR__ . '/../..' . '/src/helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Container\\' => 14,
        ),
        'M' =>
        array (
            'Monolog\\' => 8,
        ),
        'A' =>
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Monolog\\' =>
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'App\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Fixture\\Legacy\\LegacyThing' => __DIR__ . '/../..' . '/lib/Legacy.php',
        'Fixture\\Legacy\\Marker' => __DIR__ . '/../..' . '/lib/Legacy.php',
        'Fixture\\Legacy\\Mode' => __DIR__ . '/../..' . '/lib/Legacy.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitVivaceFixture::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitVivaceFixture::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitVivaceFixture::$classMap;

        }, null, ClassLoader::class);
    }
}
