<?php
/**
 * Altis Module Loader.
 *
 * DO NOT EDIT THIS FILE.
 */

// Load acme/altis-module.
require_once __DIR__ . '/acme/altis-module/load.php';
// Load custom.
require_once dirname( __DIR__ ) . DIRECTORY_SEPARATOR . 'custom-entrypoint.php';
