<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Fixture\\Legacy\\LegacyThing' => $baseDir . '/lib/Legacy.php',
    'Fixture\\Legacy\\Marker' => $baseDir . '/lib/Legacy.php',
    'Fixture\\Legacy\\Mode' => $baseDir . '/lib/Legacy.php',
);
