<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0594893ca95374e958b08ab4f24325ae
{
    public static $prefixLengthsPsr4 = array (
        'A' =>
        array (
            'Acme\\Hello\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Acme\\Hello\\' =>
        array (
            0 => __DIR__ . '/..' . '/acme/hello/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0594893ca95374e958b08ab4f24325ae::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0594893ca95374e958b08ab4f24325ae::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0594893ca95374e958b08ab4f24325ae::$classMap;

        }, null, ClassLoader::class);
    }
}
