//! `symfony/runtime`'s `Symfony\Runtime\Internal\ComposerPlugin::updateAutoloadFile`
//! (`POST_AUTOLOAD_DUMP`): writes `vendor/autoload_runtime.php`, a fixed
//! template with the runtime class and `extra.runtime` options substituted
//! in.
//!
//! Ported from `symfony/runtime` `v7.4.18` (fetched 2026-09-08, issue #93).
//! Runs from `install::write_autoload`, after `post-autoload-dump` — the
//! real plugin subscribes to that event alone, and checks `vendor/autoload.php`
//! already exists before doing anything, matching the phase it needs to run
//! in here.
//!
//! a custom `extra.runtime.autoload_template` (a project's own
//! template file, replacing the built-in one) is ported since it's a single
//! substitution away from the default path; a custom template that uses
//! tokens beyond `%runtime_class%`/`%runtime_options%` (there are none in the
//! upstream template) isn't something this port needs to anticipate.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde_json::{Map, Value};

use super::{Adapter, Ctx, php_string, phpstan::var_export};
use crate::lock::Root;

pub(super) struct SymfonyRuntime;

impl Adapter for SymfonyRuntime {
    fn plugin_names(&self) -> &'static [&'static str] {
        &["symfony/runtime"]
    }

    fn upstream_version(&self) -> &'static str {
        "v7.4.18"
    }

    fn fixture(&self) -> &'static str {
        "tests/fixtures/plugins/drupal"
    }

    fn post_autoload_dump(&self, ctx: &Ctx<'_>) -> Result<()> {
        apply(ctx.root, ctx.project_dir, ctx.vendor_dir)
    }
}

const TEMPLATE: &str = "<?php

// autoload_runtime.php @generated by Symfony Runtime

if (true === (require_once __DIR__.'/autoload.php') || empty($_SERVER['SCRIPT_FILENAME'])) {
    return;
}

$app = require $_SERVER['SCRIPT_FILENAME'];

if (!is_object($app)) {
    throw new TypeError(sprintf('Invalid return value: callable object expected, \"%s\" returned from \"%s\".', get_debug_type($app), $_SERVER['SCRIPT_FILENAME']));
}

if (is_string($_SERVER['APP_RUNTIME_OPTIONS'] ??= $_ENV['APP_RUNTIME_OPTIONS'] ?? [])) {
    $_SERVER['APP_RUNTIME_OPTIONS'] = json_decode($_SERVER['APP_RUNTIME_OPTIONS'], true, 512, JSON_THROW_ON_ERROR);
}
$_SERVER['APP_RUNTIME'] ??= $_ENV['APP_RUNTIME'] ?? %runtime_class%;
$runtime = new $_SERVER['APP_RUNTIME']($_SERVER['APP_RUNTIME_OPTIONS'] += %runtime_options%);

[$app, $args] = $runtime
    ->getResolver($app)
    ->resolve();

$app = $app(...$args);

exit(
    $runtime
        ->getRunner($app)
        ->run()
);
";

/// `ComposerPlugin::updateAutoloadFile`. A no-op when `vendor/autoload.php`
/// doesn't exist yet (matches the real plugin's own guard, though vivace
/// only ever calls this after writing it) or `extra.runtime` is literally
/// `false` (a project's explicit opt-out).
pub(super) fn apply(root: &Root, project_dir: &Path, vendor_dir: &Path) -> Result<()> {
    if !vendor_dir.join("autoload.php").is_file() {
        return Ok(());
    }
    let extra = match root.extra.get("runtime") {
        Some(Value::Bool(false)) => return Ok(()),
        Some(Value::Object(map)) => map.clone(),
        _ => Map::new(),
    };

    let template = match extra.get("autoload_template").and_then(Value::as_str) {
        Some(path) => {
            let path = if Path::new(path).is_absolute() {
                PathBuf::from(path)
            } else {
                project_dir.join(path)
            };
            fs_err::read_to_string(&path)
                .with_context(|| format!("{}: extra.runtime.autoload_template", path.display()))?
        }
        None => TEMPLATE.to_string(),
    };

    let extra_project_dir = extra.get("project_dir").and_then(Value::as_str);
    let project_dir_expr = project_dir_expr(vendor_dir, project_dir, extra_project_dir)?;

    let runtime_class = extra
        .get("class")
        .and_then(Value::as_str)
        .unwrap_or("Symfony\\Component\\Runtime\\SymfonyRuntime")
        .to_string();

    let mut options = extra;
    options.remove("class");
    options.remove("autoload_template");
    options.remove("project_dir");
    // `'['.substr(var_export($extra, true), 7, -1)."  'project_dir' => ...,\n]"`:
    // strip `var_export`'s own `array (`/`)` wrapper and splice in
    // `project_dir` as if it were declared last in the same array literal.
    // Safe to slice on byte offsets: the stripped prefix/suffix are always
    // that literal ASCII, whatever `options`' own values contain.
    let exported = var_export(&Value::Object(options), 0);
    let inner = &exported[7..exported.len() - 1];
    let runtime_options = format!("[{inner}  'project_dir' => {project_dir_expr},\n]");

    let code = template
        .replace("%runtime_class%", &php_string(&runtime_class))
        .replace("%runtime_options%", &runtime_options);

    fs_err::write(vendor_dir.join("autoload_runtime.php"), code)?;
    Ok(())
}

/// The `%project_dir%` expression: how many `dirname(__DIR__, N)` hops (or
/// plain `__DIR__` for `N == 0`) get from `vendor/` back to the project
/// (or `extra.runtime.project_dir`, if set), plus whatever path remains
/// after those hops.
fn project_dir_expr(
    vendor_dir: &Path,
    project_dir: &Path,
    extra_project_dir: Option<&str>,
) -> Result<String> {
    let target = fs_err::canonicalize(project_dir.join(extra_project_dir.unwrap_or("")))?;
    let vendor = fs_err::canonicalize(vendor_dir)?;
    let relative = make_path_relative(&target, &vendor);

    let mut nesting = 0usize;
    let mut remaining = relative.as_str();
    while let Some(stripped) = remaining.strip_prefix("../") {
        nesting += 1;
        remaining = stripped;
    }
    Ok(if nesting == 0 {
        format!("__DIR__.{}", php_string(&format!("/{remaining}")))
    } else if remaining.is_empty() {
        format!("dirname(__DIR__, {nesting})")
    } else {
        format!(
            "dirname(__DIR__, {nesting}).{}",
            php_string(&format!("/{remaining}"))
        )
    })
}

/// `Symfony\Component\Filesystem\Filesystem::makePathRelative`, POSIX paths
/// only (no drive letters) and without the "is a file" trailing-slash trim —
/// `end_path` is always a directory at this call site.
fn make_path_relative(end_path: &Path, start_path: &Path) -> String {
    let split = |p: &Path| -> Vec<String> {
        p.to_string_lossy()
            .trim_matches('/')
            .split('/')
            .fold(Vec::new(), |mut acc, segment| {
                if segment == ".." {
                    acc.pop();
                } else if segment != "." && !segment.is_empty() {
                    acc.push(segment.to_string());
                }
                acc
            })
    };
    let start = split(start_path);
    let end = split(end_path);
    let mut index = 0;
    while index < start.len() && index < end.len() && start[index] == end[index] {
        index += 1;
    }
    let depth = start.len() - index;
    let remainder = end[index..].join("/");
    if remainder.is_empty() {
        "../".repeat(depth)
    } else {
        format!("{}{remainder}/", "../".repeat(depth))
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use serde_json::json;

    use super::*;
    use crate::lock::read_root;

    fn root(extra: &Value) -> Root {
        serde_json::from_value(json!({"extra": extra})).unwrap()
    }

    #[test]
    fn apply_is_a_no_op_without_vendor_autoload() {
        let root = root(&json!({}));
        let project_dir = tempfile::tempdir().unwrap();
        let vendor_dir = project_dir.path().join("vendor");
        fs_err::create_dir_all(&vendor_dir).unwrap();
        apply(&root, project_dir.path(), &vendor_dir).unwrap();
        assert!(!vendor_dir.join("autoload_runtime.php").exists());
    }

    #[test]
    fn apply_is_a_no_op_when_runtime_is_explicitly_disabled() {
        let root = root(&json!({"runtime": false}));
        let project_dir = tempfile::tempdir().unwrap();
        let vendor_dir = project_dir.path().join("vendor");
        fs_err::create_dir_all(&vendor_dir).unwrap();
        fs_err::write(vendor_dir.join("autoload.php"), "<?php\n").unwrap();
        apply(&root, project_dir.path(), &vendor_dir).unwrap();
        assert!(!vendor_dir.join("autoload_runtime.php").exists());
    }

    #[test]
    fn project_dir_expr_one_level_below_project_root() {
        let project_dir = tempfile::tempdir().unwrap();
        let vendor_dir = project_dir.path().join("vendor");
        fs_err::create_dir_all(&vendor_dir).unwrap();
        let expr = project_dir_expr(&vendor_dir, project_dir.path(), None).unwrap();
        assert_eq!(expr, "dirname(__DIR__, 1)");
    }

    /// #93's fixture, byte-diffed against real `symfony/runtime` v7.4.18's
    /// own output (`tests/fixtures/plugins/drupal/expected/autoload_runtime.php`).
    #[test]
    fn symfony_runtime_fixture_matches_composers_golden() {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/plugins/drupal");
        let root = read_root(&dir.join("composer.json")).unwrap();
        let project_dir = tempfile::tempdir().unwrap();
        let vendor_dir = project_dir.path().join("vendor");
        fs_err::create_dir_all(&vendor_dir).unwrap();
        fs_err::write(vendor_dir.join("autoload.php"), "<?php\n").unwrap();

        apply(&root, project_dir.path(), &vendor_dir).unwrap();

        let got = fs_err::read_to_string(vendor_dir.join("autoload_runtime.php")).unwrap();
        let want =
            fs_err::read_to_string(dir.join("expected/vendor/autoload_runtime.php")).unwrap();
        assert_eq!(got, want);
    }
}
